export const FETCH_TRACKS_SUCCESS = 'FETCH_TRACKS_SUCCESS'
export const FETCH_TRACKS_FAILURE = 'FETCH_TRACKS_FAILURE'
export const FETCH_TRACKS_STARTED = 'FETCH_TRACKS_STARTED'

export const FETCH_EXECUTOR_SUCCESS = 'FETCH_EXECUTOR_SUCCESS'
export const FETCH_EXECUTOR_FAILURE = 'FETCH_EXECUTOR_FAILURE'
export const FETCH_EXECUTOR_STARTED = 'FETCH_EXECUTOR_STARTED'
